UAU:
  NAME: "UAU"
  STATES_MAP:
    U: 0
    A: 1
  MAX_DIMENSION: 1
  SEED_FREC: 0.1
  EFF_AWARE: 8.0
  MU: 0.1

CompUAU:
  NAME: "CompUAU"
  STATES_MAP:
    U: 0
    A2: 1
    A1: 2
  MAX_DIMENSION: 1
  SEED_FREC_A1: 0.1
  SEED_FREC_A2: 0.1
  EFF_AWARE_A1: 8.0
  EFF_AWARE_A2: 8.0
  MU_A1: 0.1
  MU_A2: 0.1

CompUAUCoev:
  NAME: "CompUAUCoev"
  STATES_MAP:
    UU: 0
    A1U: 1
    UA2: 2
    A1A2: 3
  MAX_DIMENSION: 1
  SEED_FREC_A1: 0.1
  SEED_FREC_A2: 0.1
  EFF_AWARE_A1: 8.0
  EFF_AWARE_A2: 8.0
  prime_A1: 0.0
  prime_A2: 0.0
  MU_A1: 0.1
  MU_A2: 0.1

CoopUAU:
  NAME: "CoopUAU"
  STATES_MAP:
    UU: 0
    A1U: 1
    UA2: 2
    A1A2: 3
  MAX_DIMENSION: 1
  SEED_FREC_A1: 0.1
  SEED_FREC_A2: 0.1
  EFF_AWARE_A1: 8.0
  EFF_AWARE_A2: 8.0
  prime_A1: 2.0
  prime_A2: 2.0
  MU_A1: 0.1
  MU_A2: 0.1

AsymmUAU:
  NAME: "AsymmUAU"
  STATES_MAP:
    UU: 0
    A1U: 1
    UA2: 2
    A1A2: 3
  MAX_DIMENSION: 1
  SEED_FREC_A1: 0.1
  SEED_FREC_A2: 0.1
  EFF_AWARE_A1: 8.0
  EFF_AWARE_A2: 8.0
  prime_A1: 0.
  prime_A2: 2.0
  MU_A1: 0.1
  MU_A2: 0.1

SCUAU:
  NAME: "SCUAU"
  STATES_MAP:
    U: 0
    A: 1
  MAX_DIMENSION: 2
  SEED_FREC: 0.1
  EFF_AWARE: 8.0
  EFF_AWARE_DELTA: 0
  MU: 0.1

SCCompUAU:
  NAME: "SCCompUAU"
  STATES_MAP:
    UU: 0
    A1U: 1
    UA2: 2
    A1A2: 3
  MAX_DIMENSION: 2
  SEED_FREC_A1: 0.1
  SEED_FREC_A2: 0.1
  EFF_AWARE_A1: 0
  EFF_AWARE_A2: 1.6
  EFF_AWARE_DELTA_A1: 2.5
  EFF_AWARE_DELTA_A2: 2.5
  prime_A1: 0.0
  prime_A2: 0.0
  MU_A1: 0.1
  MU_A2: 0.1

SCCoopUAU:
  NAME: "SCCoopUAU"
  STATES_MAP:
    UU: 0
    A1U: 1
    UA2: 2
    A1A2: 3
  MAX_DIMENSION: 2
  SEED_FREC_A1: 0.5
  SEED_FREC_A2: 0.5
  EFF_AWARE_A1: 8.0
  EFF_AWARE_A2: 8.0
  EFF_AWARE_DELTA_A1: 0.5
  EFF_AWARE_DELTA_A2: 0.5
  prime_A1: 0.5
  prime_A2: 0.5
  MU_A1: 0.1
  MU_A2: 0.1

SCAsymmUAU:
  NAME: "SCAsymmUAU"
  STATES_MAP:
    UU: 0
    A1U: 1
    UA2: 2
    A1A2: 3
  MAX_DIMENSION: 2
  SEED_FREC_A1: 0.1
  SEED_FREC_A2: 0.1
  EFF_AWARE_A1: 8.0
  EFF_AWARE_A2: 8.0
  EFF_AWARE_DELTA_A1: 8.0
  EFF_AWARE_DELTA_A2: 8.0
  prime_A1: 0.0
  prime_A2: 2.0
  MU_A1: 0.1
  MU_A2: 0.1